version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - 5000:5000
    environment:
        FLASK_DEBUG: 1    #デバッグモードON
        FLASK_APP:  "app.py"        #app.pyを起動
        FLASK_RUN_HOST: 0.0.0.0     #HOSTの設定
        YOUR_CHANNEL_ACCESS_TOKEN: 1jFv6VXOeUshS8EmUujyPMqBu0/aC63zM8bRahg0O3aGJX+Ricz+ADTZh1sq8+N+od24RX/0cbbo4AzlGjI/QW3b9cwR2QMpb4JXRwq8rpboMuRNcdF98argDq1dYFfPjDglhWEgYV8icWrzfrnUJAdB04t89/1O/w1cDnyilFU=
        YOUR_CHANNEL_SECRET: 3b85f65ffa24b2a6384df88c0eeac221
        SPOTIFY_CLIENT_ID: 9776fbcaa4304c8fbca2f75e15ef2209
        SPOTIFY_CLIENT_SECRET: f9e92e01e33b49cca0992bec07c57a8f
        DEEPFACE_HOME: ./models/
    volumes:
      - ./:/usr/src/app/
